version: '3'

services:
  db:
    image: postgres
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: postgres -p 8080
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
