import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import type { Metadata } from 'next';
import { Oxygen } from 'next/font/google';
import 'react-loading-skeleton/dist/skeleton.css';

import Header from '@/components/Header';
import './globals.css';
import Providers from './providers';

const oxygen = Oxygen({
  weight: ['300', '400', '700'],
  variable: '--font-oxygen',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Bookstore App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${oxygen.variable} antialiased`}>
        <Providers>
          <ReactQueryDevtools initialIsOpen={false} />
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
